### ISSUE TITLE
5 - Support uploads to S3 via CloudFront distribution

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1016]
The current plan is to support simple (non-chunked) uploads to a CloudFront distribution.  Chunked uploads are currently not possible when targeting a CloudFront distribution since CloudFront rips off the Authorization header containing the signature before forwarding the request on to S3.  The Authorization header is a required field in the request when using any of the S3 multipart upload REST calls, which are needed to support Fine Uploader S3's chunking and auto-resume features.  I have opened a [request in the CloudFront forums](https://forums.aws.amazon.com/thread.jspa?threadID=137626) asking for this behavior to be modified so multipart uploads requests can target a CloudFront distribution.

The planned support for this is still mostly undetermined, and it is also not determined if this support will be part of 4.0.  Making this part of 4.0 is possible, but looking less likely as I run into issues with CloudFront's handling of upload-related requests.  I'm currently struggling to get path patterns for upload requests to work.  I've opened another thread in the forum detailing my issue at https://forums.aws.amazon.com/thread.jspa?threadID=137627&tstart=0.

**Comment by cdanzig** [comment]
@rnicholus in the process of exploring chunked uploading to S3 via CloudFront. Were you ever able to get the pieces of the puzzle together?

**Comment by rnicholus** [comment]
Uploads to CloudFront _should_ work, but there appear to be some issues with CF ripping some headers off the REST requests that prevented me from certifying support for CF.  Amazon never acknowledged the issue though, even though I am able to upload files to S3 via a 3rd-party CDN without issue.

**Comment by rbliss** [comment]
@rnicholus Talked to the CloudFront guys directly. They're now saying that ALL the headers should pass through appropriately. Can you still recreate the issue or have a curl command to recreate the issue?

**Comment by rnicholus** [comment]
They told me the same thing a little while back. It isn't true, as far as I can tell. I opened up [a support request in December, detailing the issue](https://forums.aws.amazon.com/thread.jspa?threadID=167234). The sum it up, sending upload requests to S3 using the multipart upload API via CloudFront still results in removed headers. For example, x-amz-acl and all x-amz-meta headers are removed. Sending the exact same request directly to S3, or via a different CDN (such as fastly) did not result in any problems. The issue was specifically with CloudFront.

**Comment by cmwright** [comment]
It doesn't help anyone trying to use CloudFront, but we were able to get uploads via CDN working with Edgecast if someone is looking for a Fastly alternative.

**Comment by rnicholus** [comment]
Yes, uploads to S3 using Fine Uploader S# should work via *any* CDN, provided the CDN does not remove any headers.

**Comment by rbliss** [comment]
@rnicholus Cool, yeah, seems like it has been a bit frustrating getting this worked out with CloudFront. I'm in direct contact with them, if you can tip me off with an example for re-creating the issue, I can follow up with them.

**Comment by rnicholus** [comment]
@rbliss Reproducing the issue simply involves setting up Fine Uploader S3 as per usual, specifying a bucket via the new `objectProperties.bucket` option, and setting the endpoint to your CF distro. You'll see the any custom metadata (sent as x-amz-meta headers) are sent by Fine Uploader, but never actually attached to the object in S3. Since the -x-amz-acl header is stripped as well, any specified ACL value via Fine Uploader is ignored and is not attached to the object in S3.

**Comment by rbliss** [comment]
@rnicholus I'll give it a whirl and get back to you on this.

**Comment by rbliss** [comment]
@rnicholus Good news! I believe I've gotten to the bottom of the issue, and am just waiting on hearing back from the Cloudfront guys.

Appears the issue isn't a problem of Cloudfront failing to pass through headers, but of the S3 object's ACL properties being setup incorrectly when the object is both created through a Cloudfront endpoint  **and the ACL is set specifically to `private`.**

The test is straightforward: in FineUploader, try using a Cloudfront endpoint but setting the `objectProperties.acl` to `public-read` instead of FineUploader's default `private`. The object should be created properly, with the appropriate passed through meta data showing up on the object.

For some reason, only the multipart REST API uploads to S3 through Cloudfront with an ACL of `private` creates an improperly permissioned object where the bucket owner does not have permission to access the object (except strangely, deleting it). Hence the appearance that the meta data headers are not passed through, because you are not allowed to read the meta data!

Anyway, try that and tell me if I'm crazy. I do not know if other ACLs have similar problems.

**Comment by rbliss** [comment]
Note: you can lookup the ACL setting on an object with:
```
aws s3api get-object-acl --bucket <bucket> --key <object key>
```

**Comment by rnicholus** [comment]
@rbliss I remember an issue with all x-amz headers, not just the x-amz-acl. To your knowledge, the issue is on Amazon's side, is that correct? Do they have any idea when this will be fixed?

**Comment by rbliss** [comment]
@rnicholus It appears to be working for other `x-amz`

**Comment by rbliss** [comment]
I've been testing the `x-amz-meta-####` headers, and they're working great. Other headers appear to come through fine too.

After further discussion with the guys at Amazon, it appears the specific issue I was having, where the headers don't appear to come through, is really due to setting up an 'Origin Access Identity' (OAI) on Cloudfront. You have to be **very careful** when you setup an OAI to understand what's going on. An OAI will cause Cloudfront to behave *almost* as if a different user (the OAI) is creating the S3 object, rather than the user whose access key you specify in FineUploader.

An OAI is optional, but If using an OAI, you should use the acl of `bucket-owner-full-control` instead of `private` to get an S3 object that resembles what would normally happen if you hit S3 directly.

Other than that, I'm happy with the results I'm seeing from Cloudfront and it appears the earlier issues are no longer a problem.

**Comment by rnicholus** [comment]
My understanding was that an OAI is required when making signed requests, otherwise the additional headers attached to the request by CF will be rejected by S3.

In the case of "bucket-owner-full-control", I'm guessing the "owner" is CF when using an OAI. Is this your understanding? If this is true, then based on the Canned ACL descriptions, public-read will result in the same problem for the bucket owner it seems.

**Comment by rbliss** [comment]
Just a point of clarification: by signed requests, are you referring to the signed Authorization header required to authenticate a request in the S3 REST API, or signed urls used to restrict access to objects in S3?

**Comment by rnicholus** [comment]
The former. This is how Fine Uploader signs all upload requests.

**Comment by rbliss** [comment]
Just wanted to double check. You do not need an OAI to send signed requests. In fact, if you turn off the OAI (or never set one up) on your Cloudfront distro, *everything should just work* like you were interacting with S3 directly.

**Comment by rnicholus** [comment]
That wasn't my experience before. In fact, the use of OAIs in this context
was discussed on the AWS forums.  One example can be found at
https://forums.aws.amazon.com/thread.jspa?messageID=345913&#345913. I'll
have to try again without an OAI at some point.

**Comment by jasonshah** [comment]
@rbliss Have you had a chance to measure what kind of performance or stability gains you are seeing with uploads to Cloudfront vs. uploads to S3?

**Comment by rbliss** [comment]
@jasonshah, I haven't had a chance. Anecdotally, it does seem faster
@rnicholus Definitely give it a shot without OAI. Life will be glorious.

**Comment by rbliss** [comment]
I do have to warn anyone attempting to use Cloudfront, Cloudfront is a bit fiddly in terms of configuration. If you're having issues, it's likely with how you've setup Cloudfront. I can writeup configuration details if anyone is testing this.

**Comment by winzig** [comment]
I've been following this thread for a while with great interest. It sounds as if this is now working, but it's not totally clear what the procedure is to set CF up to use with FineUploader. Will this be documented?

**Comment by rnicholus** [comment]
Once this is tested and verified on our end, we'll update the [S3 Uploads feature page](http://docs.fineuploader.com/branch/master/features/s3.html) with CF-specific details.

**Comment by rbliss** [comment]
Here are my notes on setting up a proper CF distribution:

**Origin Settings**
- Restrict Bucket Access (shows up after you choose your S3 bucket) - Easiest if you choose `No` see *Notes on OAI* below.

**Default Cache Behavior Settings**
- Allowed HTTP Methods - Must choose `GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE` else you can't create an S3 object.
- Forward Query String - Must choose `Yes`, else chunked uploads will fail.
- Restrict Viewer Access - Easiest if you choose `No` else you'll have to do a lot of tweaking to send a signed Cloudfront URL in addition to all the S3 url parameters.

*Notes on OAI*: If you do setup an OAI, make sure to set FineUploader's `objectProperties.acl` to `bucket-owner-full-control` or appropriate equivalent. A Cloudfront distribution with an OAI setup on an origin pointing to a S3 bucket will cause Cloudfront to act as the OAI user when interacting with the S3 bucket regardless of the access key specified in FineUploader. Hence any objects with an acl of `private` will belong to Cloudfront's OAI user and **not the access key's user.**

**Comment by ludofleury** [comment]
@rbliss I'm trying with cloudfront, but so far the policy signature is failing (US West oregon) Could you share a bit more details ?

**Comment by ludofleury** [comment]
My bad, typo. @rbliss I confirm that with your information, the upload is going smoothly through Cloudfront to S3. Thank you very much.

**Comment by rnicholus** [comment]
Sounds like this is finally working with Fine Uploader S3. I'm continually
busy with support and licensing requests, as well as the S3 V4 support
feature, but it is still on my radar to verify and update the docs.

**Comment by andreij** [comment]
I don't know if it's the right place to ask, but maybe your answers can help other people stuck like me.

I have set up a basic uploader page, S3 + CORS and works as expected.

When I switch to the CDN upload, the response is:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
   <Code>MethodNotAllowed</Code>
   <Message>The specified method is not allowed against this resource.</Message>  
   <Method>POST</Method>
   <ResourceType>OBJECT</ResourceType>
   <RequestId>2B0507CBD403F9C3</RequestId>    
 <HostId>nEV/gHkAE3wTCKP+ZJzV/VQXNEvFP+/w2UZtyIwTrkkV+/i9aFK/Ap8qTfGfDZ+PAl2kAYD7vE4=</HostId>
</Error>
```

The response header are:

```
Access-Control-Allow-Method POST, PUT, DELETE
Access-Control-Allow-Origin *
Access-Control-Max-Age 3000
Allow GET, DELETE, HEAD, PUT
Connection keep-alive
Content-Type application/xml
Server AmazonS3
Transfer-Encoding chunked
Vary	Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Via	1.1 5d53b9570a535c2d94ce93c20abbd471.cloudfront.net (CloudFront)
X-Amz-Cf-Id dw-N_pLmOmEqlbri-B2l7l2a6TGWm2_tAhr5y9_InMU8ZuHYunZSEw==
X-Cache	Error from cloudfront
```
Below the default behavior configuration:

![schermata 2015-11-10 alle 16 13 49](https://cloud.githubusercontent.com/assets/126644/11065899/1c6da35c-87c6-11e5-85a9-14c548b694ed.png)

No OAI set. 

What I have changed into fineuploader conf is:

```			    request: {
			        endpoint: 'dqu6rri____.cloudfront.net',
			    },			   
		        objectProperties: {
			        bucket: 'fineup____-test'
			    },
```

Bucket policy:

```
{
	"Version": "2012-10-17",
	"Id": "Policy1447166234666",
	"Statement": [
		{
			"Sid": "Stmt1447166228927",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:*",
			"Resource": "arn:aws:s3:::fineup____-test/*"
		}
	]
}
```

Cors:


```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

The bucket is located in Ireland.


I'm quite clueless, so any help on how to track down the problem would help.

**Comment by rnicholus** [comment]
Youlll need to fix your comment above. Take another look.

**Comment by rnicholus** [comment]
Either way, this is a question for the AWS forums, as it appears to be some type of configuration issue on your end.

**Comment by andreij** [comment]
Dear @rnicholus if you think this is the wrong place I can remove it in order to not clutter the issue's conversation.

**Comment by rbliss** [comment]
@andreij Place it in AWS Cloudfront forums and I'll respond.

**Comment by andreij** [comment]
@rbliss Thanks! Here the follow up https://forums.aws.amazon.com/thread.jspa?threadID=219620

**Comment by nalbion** [comment]
@rnicholus @rbliss I'm getting an error when I try to upload large files to S3 through Cloudfront:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>There were headers present in the request which were not signed</Message>
  <HeadersNotSigned>x-amz-cf-id</HeadersNotSigned>
  <RequestId>123</RequestId>
  <HostId>abc=</HostId>
</Error>
```

## FineUploader config:
```javascript
var endpoint = 'mydomain.com';
var uploader = new qq.s3.FineUploader({
            // debug: true,
            element: el,
            request: {
                endpoint: 'https://' + endpoint,
                accessKey: s3AccessKey,
                params: metadata
            },
            chunking: {
                enabled: true
            },
            objectProperties: {
                bucket: bucket,
                host: endpoint,
                region: 'ap-southeast-2',
                serverSideEncryption: true
            },
            signature: {
                endpoint: domain + '/file-uploads/sign-request',
                version: 4,
                customHeaders: customHeaders
            },
```


## Cloudformation template:
```yaml
Resources:
  Distribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub files.${HostedZone}
        DefaultCacheBehavior:
          AllowedMethods:
            - "DELETE" - "GET" - "HEAD" - "OPTIONS" - "PATCH" - "POST" - "PUT"
          CachedMethods:
            - "GET" - "HEAD" - "OPTIONS"
          Compress: true
          ForwardedValues:
            QueryString: true
          TargetOriginId: "Upload Bucket"
          ViewerProtocolPolicy : "redirect-to-https"
        Enabled: true
        HttpVersion: "http2"
        Origins:
          - DomainName: !Sub ${BucketName}.s3-ap-southeast-2.amazonaws.com
            Id: "Upload Bucket"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - "GET" - "POST" - "PUT" - "DELETE"
            ExposedHeaders:
              - "Date"
              - "ETag"

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    DependsOn: Bucket
    Properties:
      Bucket:
        !Ref BucketName
      PolicyDocument:
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Action:
              - "s3:PutObject"
            Effect: "Deny"
            Resource: !Sub arn:aws:s3:::${BucketName}/*
            Principal: "*"
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption:
                  - "AES256"
          - Sid: DenyUnEncryptedObjectUploads
            Action:
              - "s3:PutObject"
            Effect: "Deny"
            Resource: !Sub arn:aws:s3:::${BucketName}/*
            Principal: "*"
            Condition:
              StringEquals:
                s3:x-amz-server-side-encryption:
                  - !Ref AWS::NoValue
```
